### PR TITLE
55-creating-robust-and-complete-test-suite

### PR DESCRIPTION
**Pull request by uedar**
## Changes
- Add pytest to check if the calculation is successful
  - It is assumed that to run on docker container
  - still only QE serial calculation test
  -  loose calculation conditions to complete calculations quickly
- Created docker file for testing
  - All developers can use the same environment and versions for development
  - should be able to run pytest, including calculations, on your local PC

 - Implement link function for QE_batch

## Docker container environment
- ubuntu: 20.04
- Quantum espresso: 7.0
- python: 3.10
- open MPI: 4.0.3 

## How to run pytest in Docker
- Install Docker Desktop from [here](https://docs.docker.com/desktop/install/mac-install/)

- Run these commands on your local repository (`./STATE-BATCH`)
```bash
# build and start container (the first time will take about 10 minutes)
$ docker compose up -d
# run pytest in docker container
$ docker exec -it state_batch pytest -s ./STATE-BATCH
```

## Todo (future updates)
- Add STATE execution environment
- Enhance the number of test suite
- Enable testing on github (github actions)

### CODE REVIEW

**Comment by kimrojas** [comment]
> Docker container environment

Can STATE also be added ?

**Comment by kimrojas** [comment]
> * Add STATE execution environment

Will this be applied to this pull request ? or in future updates ?

> * Enhance the number of test suite
> * Enable testing on github (github actions)

Won't it be hard to run on github actions w.r.t calculation time ?

**Comment by uedar** [comment]
@kimrojas 
Thanks for your comments.
>
>- Add STATE execution environment
>- Enhance the number of test suite
>- Enable testing on github (github actions)
>
I hope to be able to implement these todo's in the future after merging this pull request.

STATE is not an opensource, so I don't know how to do it yet. Do you have any good ideas?

In the case of H single_atom in this pull request, the calculation was completed within 10 seconds in my docker environment.

```
WAIT        timestamp:  11/23/2022, 03:46:52
RUN         timestamp:  11/23/2022, 03:46:52
DONE        timestamp:  11/23/2022, 03:46:58
ARCHIVED    timestamp:  11/23/2022, 03:46:58
```
I will try github actions later　(If it takes too long time and is inconvenient, stop using it.)

**Comment by hhlim12** [comment]
I have run the `docker compose up` and it shows like this:
image

However when I run `docker exec -it state_batch pytest -s ./STATE-BATCH`, I got error:
```
Error response from daemon: Container b63d1c38543d3a4c72a270dd1a779dc51a969b8a6d4705acbce4781d6b0a9b35 is not running
```

Any idea?

**Comment by hhlim12** [comment]
> STATE is not an opensource, so I don't know how to do it yet. Do you have any good ideas?
Based on your explanation, this docker will be used only for developer, right? So All of us have STATE src already, so is it possible to link to the src in local pc ? We should not put STATE src in public domain..

**Comment by kimrojas** [comment]
When I do `docker compose up -d`. I get
```bash
[+] Building 1.7s (6/11)
 => [internal] load build definition from Dockerfile                                                                                             0.0s
 => => transferring dockerfile: 32B                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                0.0s
 => => transferring context: 2B                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                  1.0s
 => [1/8] FROM docker.io/library/ubuntu:20.04@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd                            0.0s
 => CACHED [2/8] RUN apt update                                                                                                                  0.0s
 => ERROR [3/8] RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC     apt install -y sudo wget build-essential     gfortran cmake openmpi-bin libop  0.6s
------
 > [3/8] RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC     apt install -y sudo wget build-essential     gfortran cmake openmpi-bin libopenmpi-dev
git software-properties-common curl:
#0 0.359
#0 0.359 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#0 0.359
#0 0.371 Reading package lists...
#0 0.529 Building dependency tree...
#0 0.562 Reading state information...
#0 0.566 Package gfortran is not available, but is referred to by another package.
#0 0.566 This may mean that the package is missing, has been obsoleted, or
#0 0.566 is only available from another source
#0 0.566
#0 0.566 E: Package 'gfortran' has no installation candidate
#0 0.566 E: Unable to locate package openmpi-bin
#0 0.566 E: Unable to locate package libopenmpi-dev
------
failed to solve: executor failed running [/bin/sh -c DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC     apt install -y sudo wget build-essential     gfortran cmake openmpi-bin libopenmpi-dev     git software-properties-common curl]: exit code: 100
```

**Comment by hhlim12** [comment]
> I have run the `docker compose up` and it shows like this: image
> 
> However when I run `docker exec -it state_batch pytest -s ./STATE-BATCH`, I got error:
> 
> ```
> Error response from daemon: Container b63d1c38543d3a4c72a270dd1a779dc51a969b8a6d4705acbce4781d6b0a9b35 is not running
> ```
> 
> Any idea?

The problem solved when I updated my repository using `gitpull`. Now it seems okay for me (I use Mac OS)
image

**Comment by uedar** [comment]
@kimrojas 
Could you please try to build with no-cache?
```
docker build --no-cache .
```

**Comment by hhlim12** [comment]
I have few questions regarding this PR:
1. The number of cores used for testing (specified in yaml file) is 16. I think it is too high for local PC, how about reduce it to 4 and further reduce the vacuum (e.g., 8 Å).
2. In Yaml file, it is specified the name of json file is `unique_id.json`, but why in the testing it requests the `file_prefix.json`?
The file prefix is the default value that will be used when the archive name format is not specified in yaml file..I'm quite curious why the testing pass this. I suggest to set the default  value for archived file (by simply remove the `name_format` key in yaml) since we can not know the unique number beforehand.
image

**Comment by hhlim12** [comment]
I have few questions regarding this PR:
1. The number of cores used for testing (specified in yaml file) is 16. I think it is too high for local PC, how about reduce it to 4 and further reduce the vacuum (e.g., 8 Å).
2. In Yaml file, it is specified the name of json file is `unique_id.json`, but why in the testing it requests the `file_prefix.json`?
The file prefix is the default value that will be used when the archive name format is not specified in yaml file..I'm quite curious why the testing pass this. I suggest to set the default  value for archived file (by simply remove the `name_format` key in yaml) since we can not know the unique number beforehand.
image

**Comment by uedar** [comment]
@hhlim12 , Thank you for suggestions.
There was a typo in the `archive_option` of the yaml file. 
It seems that the archived file was created with the default file_prefix because the name_format was not read correctly.
It has been corrected and I also removed `name_format` key.

**Comment by hhlim12** [comment]
> @hhlim12 , Thank you for suggestions. There was a typo in the `archive_option` of the yaml file. It seems that the archived file was created with the default file_prefix because the name_format was not read correctly. It has been corrected and I also removed `name_format` key.
> 
> I think it is good to be able to validate whether the key name are correct when reading the yaml file.

I see, now it makes sense.
I agree that it is good idea to validate the name format.
Then we should specify name format in the yaml file.
```yaml
archive_option:
     name_format: test
     file_format: json                    # Type of archive file. Can be json or db
```

and then in the `test_calculator.py` specify
```python
json_file_name = Batch_obj.archive_option.get("name_format") + "." + "Batch_obj.archive_option.get("file_format")"
```
I'm sorry for the trouble..

**Comment by uedar** [comment]
Thank you.  File names are now retrieved from `archive_option`.

**Comment by kimrojas** [comment]
> Based on your explanation, this docker will be used only for developer, right? So All of us have STATE src already, so is it possible to link to the src in local pc ? We should not put STATE src in public domain..

We can use the `COPY` command in the dockerfile for this one. But this assumes that that source code is just beside the Dockerfile. 

More information on this in [here](https://stackoverflow.com/questions/34872620/how-to-access-local-file-when-building-from-dockerfile)

And BTW, this can only be done locally. If we try to use the github actions to do this, there will be a need to upload the source files into the repository. I'm not sure how to keep it private in that sense. Maybe have some form of password  authentication?

Also, we may need a generic build config file for general usage in different architecture. Do you know if this is possible ?

**Comment by kimrojas** [comment]
> @kimrojas Could you please try to build with no-cache?
> 
> ```
> docker build --no-cache .
> ```

@uedar Your solution works. Also it works when I use the old docker-compose 
```bash
docker-compose up -d

**Comment by kimrojas** [comment]
@uedar Can you please add an entry to the README.md file ?

**Comment by hhlim12** [comment]
Also, can you add the instruction to stop the docker for running in background?
I think the command is `docker compose stop`

**Comment by uedar** [comment]
Added to the README.md about how to use docker.

**Comment by hhlim12** [comment]
Thank you very much for the modification !. I think we can merge this PR now. Further change can be made in new PR.

**Review by hhlim12 — APPROVED** [review]
I have run the pytest using docker on Mac OS. I passed the test using Espresso. The procedure is already documented in README.

**Pull request merged**
