### PR TITLE
Feature jobscript gen

### PR DESCRIPTION
**Pull request by hhlim12**
I made changes following @kimrojas 's review
- Move the write_jobscript function into jobutils.py
- If the mpi_command keyword is `none` proceed directly to executable.
```
 if mpi_command is not None:
        command = f"{mpi_command} -np {n_cpus} ./{pw_name} < {input_file} > {output_file}"
 else:
        command = f"./{pw_name} < {input_file} > {output_file}"
```

### CODE REVIEW

**Comment by kimrojas** [comment]
@hhlim12 Is this the same pull request ? I couldn't find my comment.

**Comment by hhlim12** [comment]
@kimrojas , This is a new pull request. I closed the previous one. I thought when modify the code we have to redo the pull request (?)

**Comment by kimrojas** [comment]
@hhlim12 i see. I think there is no need to create new one. You just need to edit and push again. This change will be reflected in the pull request automatically (there is a 1-1 relationship between the branch and pull request). If you checked my previous pull request, you will see a new commit after your comments. This is what happens if you push into the branch after the pull request.

**Comment by hhlim12** [comment]
@kimrojas , Thank you for the information. I just know it.
Let me reopen the old one..

**Pull request closed without merging**
