### PR TITLE
28 feature enhancement directory iterators should start from 1

### PR DESCRIPTION
**Pull request by kimrojas**
Edited the starting number of directory names. 

OLD BEHAVIOR
starts from 0000

NEW BEHAVIOR
starts from 0001

Effect: 1-1 mapping of atoms_to_run systems and TASK_ID  indexes

### CODE REVIEW

**Comment by kimrojas** [comment]
New merged might make some bugs, I'll fix it in a later issue

**Comment by uedar** [comment]
Could you please resolve the conflict?

**Comment by kimrojas** [comment]
@uedar May I ask for your review?

**Review by uedar — APPROVED** [review]
I have checked this changes using examples and seems good 👍

**Pull request merged**
