### PR TITLE
add skipinitialspace=True

### PR DESCRIPTION
**Pull request by hhlim12**
add `skipinitialspace=True` in the `pd.read_csv()`. This option remove the spaces **after** delimiter at header and body of csv. So the following should be fine.
```
Species, PSEUDOS,      XCTYPE
```

I understand such mistake might happen since space after comma is kind of convention in text writing.  

For the case of space **before** the delimiter, it seems pandas has no convenient way to address this. Anyway, pandas will raise error in that case so I think it is fine. Just warn the user in the manual for not putting any space in the csv. 

But if you think it is necessary I can write the code to remove the space **before** delimiter. But it may involve iterating through all csv file to check and strip the space..In my opinion this is not so necessary.

### CODE REVIEW

**Comment by kimrojas** [comment]
> For the case of space **before** the delimiter, it seems pandas has no convenient way to address this. Anyway, pandas will raise error in that case so I think it is fine. Just warn the user in the manual for not putting any space in the csv.
> 
> But if you think it is necessary I can write the code to remove the space **before** delimiter. But it may involve iterating through all csv file to check and strip the space..In my opinion this is not so necessary.

Hi @hhlim12 . No need to iterate or process the csv file. We can just apply `strip` to both header and string columns via pandas. 
Here is how I do it. 
```python
import pandas as pd

df = pd.read_csv("data.csv")

print("Initial \n", df)

# APPLY STRIP TO HEADERS
df.columns = df.columns.str.strip()

# APPLY STRIP TO OBJECTS (String columns only)
for col_data in [df[col] for col in df.columns if df[col].dtypes == "object"]:
    col_data = col_data.str.strip()

print("Final \n", df)

```

**Comment by kimrojas** [comment]
@hhlim12 No need to process the csv. We can handle it via pandas by applying strip to header and `object` colums. 
Here is how to do it. 
```python
#!/usr/bin/env python3
import pandas as pd

df = pd.read_csv("data.csv")

print("Initial \n", df)

# APPLY STRIP TO HEADERS
df.columns = df.columns.str.strip()

# APPLY STRIP TO OBJECTS (No applied to int or float)
for c in [c for c in df.columns if df[c].dtypes == "object"]:
    df[c] = df[c].str.strip()

print("Final \n", df)
```

The output should be like this 
```bash
Initial
   col1 col2    col3     col4  col5
0    q       a   z         1   1.1
1    w       s    x        2   2.2
2    e       d  c          3   3.3
3    r       f    v        4   4.4
Final
   col1 col2 col3  col4  col5
0    q    a    z     1   1.1
1    w    s    x     2   2.2
2    e    d    c     3   3.3
3    r    f    v     4   4.4
```

**Comment by hhlim12** [comment]
I followed @kimrojas suggestion which work perfectly..

**Review by kimrojas — APPROVED** [review]
Great!  Approving the merge

**Pull request merged**
