### PR TITLE
20 feature enhancement build module add lattice constant functionality

### PR DESCRIPTION
**Pull request by uedar**
- lattice constant can be read from csv file
  - Multiple values can be used by separating with `|`.( e.g. hcp: a|c = `2.66|4.94`)
  - also possible to get it from ase as before
- use all example files in unit test(test_build_atoms_structure)
  - It is commonized in `conftest.py`, so it should be usable when adding other tests.

### CODE REVIEW

**Comment by kimrojas** [comment]
@uedar  We have a bug when using adsorption system. 
When ran it results in 
```bash
  File "/home/krojas/github_files/statebatch-files/STATE-BATCH/examples/adsorption/run.py", line 7, in <module>
    Batch_obj.prerun()
  File "/home/krojas/github_files/statebatch-files/STATE-BATCH/examples/adsorption/../../statebatch/statebatch/STATEbatch.py", line 67, in prerun
    _, input_file, output_file = build(atom_to_run=atom_to_run,
  File "/home/krojas/github_files/statebatch-files/STATE-BATCH/examples/adsorption/../../statebatch/statebatch/build.py", line 14, in build
    atoms_obj, _atoms = build_atoms_structure(atom_to_run, system_spec)
  File "/home/krojas/github_files/statebatch-files/STATE-BATCH/examples/adsorption/../../statebatch/statebatch/build.py", line 119, in build_atoms_structure
    lattice_constants = atom_to_run["Latticeconstant"].split('|')
AttributeError: 'float' object has no attribute 'split'
```

I think this is because of the file type of Lattice constant. Its being automatically parsed as float (when only 1 number is detected). 

## THE HOTFIX SOLUTION 
change the following:
```python
# CHANGE
#atom_to_run["Latticeconstant"].split('|')
# TO
# str(atom_to_run["Latticeconstant"]).split('|')
```

## THE LONG TERM SOLUTION (Ideas)
1. Change the behavior of the CSV parser (most likely fixing the dtype in the pandas csv reader).  Make string as default dtype. Downside: This will make us manually set all dtypes for accepted parameters.

**Comment by uedar** [comment]
@kimrojas 
Thanks for finding the bug, and the shortening of the if block was helpful.

**Review by kimrojas — CHANGES_REQUESTED** [review]
All good. Thank you so much for the pytest, it becomes easy to test.  

I have a comment. As we create more functions, the meaning / types of variables become confusing. Can you please add the `return` section to the function description comment ?

for example 
```python
    """Build

    Atomic structure builder

    Parameters
    ----------
    atom_to_run : dict
        Atomic structure dictionary
    system_spec : dict
        Information about the system to be calculated
    
    Return 
    ----------
    atoms_obj : ASE atom class obj
        An instance an ASE atom class object to calculate
    _atoms :  ---
        ------- 

    """

```

**Review by kimrojas — APPROVED** [review]
Great! Thank you.

**Pull request merged**
